[package]
name = "dsdmona"
version = "0.1.0"
authors = ["Rexagon <reide740@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
dialoguer = "0.7"
libc = "0.2"
walkdir = "2.3"
x11 = { version = "2.18", features = ["xlib"] }
